services:
  redsocks:
    image: mietzen/redsocks-proxy:stable
    hostname: redsocks
    ports:
      - "5900:5900"
      - "6080:6080"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      PROXY_TYPE: ${PROXY_TYPE}
      PROXY_SERVER: ${PROXY_SERVER}
      PROXY_PORT: ${PROXY_PORT}
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}
    dns: 9.9.9.9
    restart: unless-stopped
  grass-desktop:
    build:
      context: .
      dockerfile: grass-desktop.dockerfile
    environment:
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      MAX_RETRY_MULTIPLIER: ${MAX_RETRY_MULTIPLIER}
    depends_on:
      redsocks:
        condition: service_healthy
    network_mode: service:redsocks
    tty: true
    stdin_open: true
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./
    #       target: /app/

